services:
- type: web
  name: concesionario-api
  env: docker
  buildCommand: mvn clean package -DskipTests
  startCommand: java -jar /app.jar
  dockerfilePath: ./Dockerfile
  envVars:
  - key: SPRING_PROFILES_ACTIVE
    value: prod
  disk:
    name: concesionario-api-disk
    sizeGB: 10
    mountPath: /uploads